import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { describe, it } from 'node:test';

describe('unified dashboard workspace', () => {
  it('uses one overview request and one linked analytics workspace', () => {
    const view = readFileSync(new URL('./views/DashboardView.tsx', import.meta.url), 'utf8');
    const service = readFileSync(new URL('../../services/dashboardService.ts', import.meta.url), 'utf8');
    const workspace = readFileSync(new URL('./components/DashboardAnalyticsWorkspace.tsx', import.meta.url), 'utf8');
    const chart = readFileSync(new URL('./components/DashboardPrimaryChart.tsx', import.meta.url), 'utf8');
    const bars = readFileSync(new URL('./components/RoundedBarChart.tsx', import.meta.url), 'utf8');
    const insights = readFileSync(new URL('./components/DashboardInsightsPanel.tsx', import.meta.url), 'utf8');
    const counter = readFileSync(new URL('./components/AnimatedCounter.tsx', import.meta.url), 'utf8');
    const animation = readFileSync(new URL('./dashboardAnimation.ts', import.meta.url), 'utf8');
    const provider = readFileSync(new URL('../../providers/AnimationPreferenceProvider.tsx', import.meta.url), 'utf8');
    const app = readFileSync(new URL('../../App.tsx', import.meta.url), 'utf8');

    assert.equal(view.includes('DashboardAnalyticsWorkspace'), true);
    assert.equal(view.includes('HistoricalAnalyticsPanel'), false);
    assert.equal(view.includes('CatalogMetricsModule'), false);
    assert.equal(view.includes('Visao executiva'), false);
    assert.equal(view.includes('Dashboard da MK Maker'), false);
    assert.equal(service.includes('/api/dashboard/overview'), true);
    assert.equal(workspace.includes('PeriodSelector'), true);
    assert.equal(workspace.includes('AnimatedCounter'), true);
    assert.equal(workspace.includes('staggerChildren'), true);
    assert.equal(workspace.includes('useLocation'), true);
    assert.equal(workspace.includes('location.key'), true);
    assert.equal(workspace.includes('overview.data.generatedAt'), true);
    assert.equal(workspace.includes('animationRunKey'), true);
    assert.equal(workspace.includes('dashboardAnimation.pageDuration'), true);
    assert.equal(workspace.includes('dashboardAnimation.cardStagger'), true);
    assert.equal(workspace.includes('dashboardAnimation.cardDuration'), true);
    assert.equal(workspace.includes('metricOptions'), true);
    assert.equal(workspace.includes('comparisonPoints'), true);
    assert.equal(workspace.includes('Exportar CSV'), true);
    assert.equal(workspace.includes('Atualizado'), true);
    assert.equal(chart.includes('RoundedBarChart'), true);
    assert.equal(bars.includes('motion.rect'), true);
    assert.equal(bars.includes('rx='), true);
    assert.equal(bars.includes('highlightMax'), true);
    assert.equal(bars.includes('staggerChildren'), true);
    assert.equal(bars.includes('dashboardAnimation.chartDuration'), true);
    assert.equal(bars.includes('dashboardAnimation.maxElementDelay'), true);
    assert.equal(bars.includes('delay: Math.min(index * barDelayStep'), true);
    assert.equal(counter.includes('useState(0)'), true);
    assert.equal(counter.includes('dashboardAnimation.counterDurationMs'), true);
    assert.equal(animation.includes('pageDuration: 20'), true);
    assert.equal(animation.includes('cardDuration: 24'), true);
    assert.equal(animation.includes('chartDuration: 36'), true);
    assert.equal(animation.includes('compactChartDuration: 24'), true);
    assert.equal(animation.includes('counterDurationMs: 32000'), true);
    assert.equal(animation.includes('counterFrameMs: 80'), true);
    assert.equal(animation.includes('interface DashboardAnimationConfig'), true);
    assert.equal(animation.includes('as const satisfies DashboardAnimationConfig'), true);
    assert.equal(animation.includes('respectReducedMotion: true'), true);
    assert.equal(animation.includes('forceMotion'), false);
    assert.equal(animation.includes('shouldReduceDashboardMotion'), true);
    assert.equal(animation.includes('prefersReducedMotion ?? false'), true);
    assert.equal(animation.includes('maxElementDelay: 12'), true);
    assert.equal(counter.includes('setTimeout(update'), true);
    assert.equal(counter.includes('clearTimeout'), true);
    assert.equal(counter.includes('useAnimationPreference'), true);
    assert.equal(bars.includes('useAnimationPreference'), true);
    assert.equal(workspace.includes('useAnimationPreference'), true);
    assert.equal(insights.includes('useAnimationPreference'), true);
    assert.equal(counter.includes('useReducedMotion'), false);
    assert.equal(bars.includes('useReducedMotion'), false);
    assert.equal(workspace.includes('useReducedMotion'), false);
    assert.equal(insights.includes('useReducedMotion'), false);
    assert.equal(provider.includes('MotionConfig'), true);
    assert.equal(provider.includes('useReducedMotion'), true);
    assert.equal(provider.includes('shouldReduceDashboardMotion'), true);
    assert.equal(provider.includes('createContext'), true);
    assert.equal(provider.includes("reducedMotion={value.motionConfigReducedMotion}"), true);
    assert.equal(app.includes('AnimationPreferenceProvider'), true);
    assert.equal(insights.includes('Vendas'), true);
    assert.equal(insights.includes('Estoque'), true);
    assert.equal(insights.includes('Categorias'), true);
    assert.equal(insights.includes('Qualidade'), true);
    assert.equal(insights.includes('AnimatedCounter'), true);
    assert.equal(insights.includes('dashboardAnimation.cardDuration'), true);
    assert.equal(insights.includes('dashboardAnimation.cardStagger'), true);
    assert.equal(insights.includes('Taxa de conclusao'), true);
    assert.equal(insights.includes('Tempo ate confirmar'), true);
    assert.equal(insights.includes('Maior lucro realizado'), true);
  });
});
