import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  safe: { flex: 1 },
  header: {
    paddingHorizontal: 18,
    paddingTop: 18,
    paddingBottom: 12,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  appName: { fontSize: 19, fontWeight: '900' },
  headerSub: { marginTop: 2, fontSize: 12 },
  modeButton: { borderWidth: 1, borderRadius: 999, paddingHorizontal: 12, paddingVertical: 8 },
  body: { flex: 1 },
  content: { padding: 18, gap: 14, paddingBottom: 104 },
  surface: { borderWidth: 1, borderRadius: 8, padding: 16, gap: 12 },
  heroCard: { minHeight: 260, justifyContent: 'center' },
  title: { fontSize: 24, fontWeight: '900', lineHeight: 30 },
  paragraph: { fontSize: 14, lineHeight: 21 },
  input: { borderWidth: 1, borderRadius: 8, paddingHorizontal: 12, paddingVertical: 12, fontSize: 15 },
  button: { minHeight: 44, borderRadius: 8, alignItems: 'center', justifyContent: 'center', paddingHorizontal: 14 },
  buttonText: { fontWeight: '900' },
  bannerWrap: { height: 220, borderRadius: 8, overflow: 'hidden' },
  banner: { width: '100%', height: '100%' },
  bannerOverlay: {
    ...StyleSheet.absoluteFill,
    backgroundColor: 'rgba(0,0,0,0.38)',
    padding: 18,
    justifyContent: 'flex-end',
  },
  storeLogoFrame: {
    width: 76,
    height: 54,
    borderRadius: 8,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 8,
    marginBottom: 10,
  },
  storeLogoImage: {
    width: '100%',
    height: '100%',
  },
  storeLogoText: {
    color: '#c98f86',
    textAlign: 'center',
    textAlignVertical: 'center',
    fontWeight: '900',
    fontSize: 22,
  },
  bannerTitle: { color: '#fff', fontSize: 24, fontWeight: '900' },
  bannerText: { color: '#d9fbe7', marginTop: 3 },
  sectionTitleRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  sectionTitle: { fontSize: 20, fontWeight: '900' },
  grid: { gap: 12 },
  productCard: { borderWidth: 1, borderRadius: 8, padding: 12, gap: 7 },
  productImage: { width: '100%', height: 170, borderRadius: 8 },
  detailImage: { width: '100%', height: 300, borderRadius: 8 },
  productName: { fontSize: 16, fontWeight: '900' },
  price: { fontSize: 17, fontWeight: '900' },
  priceLarge: { fontSize: 24, fontWeight: '900' },
  label: { fontWeight: '900', fontSize: 15 },
  chips: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  chip: { borderWidth: 1, borderRadius: 999, paddingHorizontal: 12, paddingVertical: 8 },
  rowCard: { gap: 9 },
  qtyRow: { flexDirection: 'row', alignItems: 'center', gap: 12 },
  qtyText: { minWidth: 28, textAlign: 'center', fontWeight: '900' },
  inlineActions: { flexDirection: 'row', gap: 8, flexWrap: 'wrap' },
  nav: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    minHeight: 70,
    borderTopWidth: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-around',
    paddingBottom: 8,
  },
  navItem: { paddingHorizontal: 4, paddingVertical: 10, alignItems: 'center' },
  usageBlock: { gap: 6, marginTop: 8 },
  usageHeader: { flexDirection: 'row', justifyContent: 'space-between' },
  progress: { height: 8, borderRadius: 999, overflow: 'hidden' },
  progressFill: { height: 8, borderRadius: 999 },
  qrMock: {
    minHeight: 180,
    borderWidth: 1,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
    padding: 14,
    gap: 8,
  },
});
